// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package dma_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 7;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_src_ptr_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_dst_ptr_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_addr_ptr_reg_t;

  typedef struct packed {
    logic [15:0] q;
    logic        qe;
  } dma_reg2hw_size_d1_reg_t;

  typedef struct packed {
    logic [15:0] q;
  } dma_reg2hw_size_d2_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        re;
    } ready;
    struct packed {
      logic        q;
      logic        re;
    } window_done;
  } dma_reg2hw_status_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } dma_reg2hw_src_ptr_inc_d1_reg_t;

  typedef struct packed {
    logic [22:0] q;
  } dma_reg2hw_src_ptr_inc_d2_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } dma_reg2hw_dst_ptr_inc_d1_reg_t;

  typedef struct packed {
    logic [22:0] q;
  } dma_reg2hw_dst_ptr_inc_d2_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } rx_trigger_slot;
    struct packed {
      logic [15:0] q;
    } tx_trigger_slot;
  } dma_reg2hw_slot_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } dma_reg2hw_src_data_type_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } dma_reg2hw_dst_data_type_reg_t;

  typedef struct packed {
    logic        q;
  } dma_reg2hw_sign_ext_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } dma_reg2hw_mode_reg_t;

  typedef struct packed {
    logic        q;
  } dma_reg2hw_hw_fifo_en_reg_t;

  typedef struct packed {
    logic        q;
  } dma_reg2hw_dim_config_reg_t;

  typedef struct packed {
    logic        q;
  } dma_reg2hw_dim_inv_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } dma_reg2hw_pad_top_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } dma_reg2hw_pad_bottom_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } dma_reg2hw_pad_right_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } dma_reg2hw_pad_left_reg_t;

  typedef struct packed {
    logic [12:0] q;
    logic        qe;
  } dma_reg2hw_window_size_reg_t;

  typedef struct packed {
    logic [7:0]  q;
  } dma_reg2hw_window_count_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } transaction_done;
    struct packed {
      logic        q;
    } window_done;
  } dma_reg2hw_interrupt_en_reg_t;

  typedef struct packed {
    logic        q;
    logic        re;
  } dma_reg2hw_transaction_ifr_reg_t;

  typedef struct packed {
    logic        q;
    logic        re;
  } dma_reg2hw_window_ifr_reg_t;

  typedef struct packed {
    logic        q;
  } dma_reg2hw_hw_config_mode_reg_t;

  typedef struct packed {
    logic [7:0]  q;
  } dma_reg2hw_slot_wait_counter_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } dma_hw2reg_src_ptr_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } dma_hw2reg_dst_ptr_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } dma_hw2reg_addr_ptr_reg_t;

  typedef struct packed {
    logic [15:0] d;
    logic        de;
  } dma_hw2reg_size_d1_reg_t;

  typedef struct packed {
    logic [15:0] d;
    logic        de;
  } dma_hw2reg_size_d2_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } ready;
    struct packed {
      logic        d;
    } window_done;
  } dma_hw2reg_status_reg_t;

  typedef struct packed {
    logic [5:0]  d;
    logic        de;
  } dma_hw2reg_src_ptr_inc_d1_reg_t;

  typedef struct packed {
    logic [22:0] d;
    logic        de;
  } dma_hw2reg_src_ptr_inc_d2_reg_t;

  typedef struct packed {
    logic [5:0]  d;
    logic        de;
  } dma_hw2reg_dst_ptr_inc_d1_reg_t;

  typedef struct packed {
    logic [22:0] d;
    logic        de;
  } dma_hw2reg_dst_ptr_inc_d2_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] d;
      logic        de;
    } rx_trigger_slot;
    struct packed {
      logic [15:0] d;
      logic        de;
    } tx_trigger_slot;
  } dma_hw2reg_slot_reg_t;

  typedef struct packed {
    logic [1:0]  d;
    logic        de;
  } dma_hw2reg_src_data_type_reg_t;

  typedef struct packed {
    logic [1:0]  d;
    logic        de;
  } dma_hw2reg_dst_data_type_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } dma_hw2reg_sign_ext_reg_t;

  typedef struct packed {
    logic [1:0]  d;
    logic        de;
  } dma_hw2reg_mode_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } dma_hw2reg_hw_fifo_en_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } dma_hw2reg_dim_config_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } dma_hw2reg_dim_inv_reg_t;

  typedef struct packed {
    logic [5:0]  d;
    logic        de;
  } dma_hw2reg_pad_top_reg_t;

  typedef struct packed {
    logic [5:0]  d;
    logic        de;
  } dma_hw2reg_pad_bottom_reg_t;

  typedef struct packed {
    logic [5:0]  d;
    logic        de;
  } dma_hw2reg_pad_right_reg_t;

  typedef struct packed {
    logic [5:0]  d;
    logic        de;
  } dma_hw2reg_pad_left_reg_t;

  typedef struct packed {
    logic [12:0] d;
    logic        de;
  } dma_hw2reg_window_size_reg_t;

  typedef struct packed {
    logic [7:0]  d;
    logic        de;
  } dma_hw2reg_window_count_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } transaction_done;
    struct packed {
      logic        d;
      logic        de;
    } window_done;
  } dma_hw2reg_interrupt_en_reg_t;

  typedef struct packed {
    logic        d;
  } dma_hw2reg_transaction_ifr_reg_t;

  typedef struct packed {
    logic        d;
  } dma_hw2reg_window_ifr_reg_t;

  typedef struct packed {
    logic [7:0]  d;
    logic        de;
  } dma_hw2reg_slot_wait_counter_reg_t;

  // Register -> HW type
  typedef struct packed {
    dma_reg2hw_src_ptr_reg_t src_ptr; // [293:262]
    dma_reg2hw_dst_ptr_reg_t dst_ptr; // [261:230]
    dma_reg2hw_addr_ptr_reg_t addr_ptr; // [229:198]
    dma_reg2hw_size_d1_reg_t size_d1; // [197:181]
    dma_reg2hw_size_d2_reg_t size_d2; // [180:165]
    dma_reg2hw_status_reg_t status; // [164:161]
    dma_reg2hw_src_ptr_inc_d1_reg_t src_ptr_inc_d1; // [160:155]
    dma_reg2hw_src_ptr_inc_d2_reg_t src_ptr_inc_d2; // [154:132]
    dma_reg2hw_dst_ptr_inc_d1_reg_t dst_ptr_inc_d1; // [131:126]
    dma_reg2hw_dst_ptr_inc_d2_reg_t dst_ptr_inc_d2; // [125:103]
    dma_reg2hw_slot_reg_t slot; // [102:71]
    dma_reg2hw_src_data_type_reg_t src_data_type; // [70:69]
    dma_reg2hw_dst_data_type_reg_t dst_data_type; // [68:67]
    dma_reg2hw_sign_ext_reg_t sign_ext; // [66:66]
    dma_reg2hw_mode_reg_t mode; // [65:64]
    dma_reg2hw_hw_fifo_en_reg_t hw_fifo_en; // [63:63]
    dma_reg2hw_dim_config_reg_t dim_config; // [62:62]
    dma_reg2hw_dim_inv_reg_t dim_inv; // [61:61]
    dma_reg2hw_pad_top_reg_t pad_top; // [60:55]
    dma_reg2hw_pad_bottom_reg_t pad_bottom; // [54:49]
    dma_reg2hw_pad_right_reg_t pad_right; // [48:43]
    dma_reg2hw_pad_left_reg_t pad_left; // [42:37]
    dma_reg2hw_window_size_reg_t window_size; // [36:23]
    dma_reg2hw_window_count_reg_t window_count; // [22:15]
    dma_reg2hw_interrupt_en_reg_t interrupt_en; // [14:13]
    dma_reg2hw_transaction_ifr_reg_t transaction_ifr; // [12:11]
    dma_reg2hw_window_ifr_reg_t window_ifr; // [10:9]
    dma_reg2hw_hw_config_mode_reg_t hw_config_mode; // [8:8]
    dma_reg2hw_slot_wait_counter_reg_t slot_wait_counter; // [7:0]
  } dma_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    dma_hw2reg_src_ptr_reg_t src_ptr; // [313:281]
    dma_hw2reg_dst_ptr_reg_t dst_ptr; // [280:248]
    dma_hw2reg_addr_ptr_reg_t addr_ptr; // [247:215]
    dma_hw2reg_size_d1_reg_t size_d1; // [214:198]
    dma_hw2reg_size_d2_reg_t size_d2; // [197:181]
    dma_hw2reg_status_reg_t status; // [180:179]
    dma_hw2reg_src_ptr_inc_d1_reg_t src_ptr_inc_d1; // [178:172]
    dma_hw2reg_src_ptr_inc_d2_reg_t src_ptr_inc_d2; // [171:148]
    dma_hw2reg_dst_ptr_inc_d1_reg_t dst_ptr_inc_d1; // [147:141]
    dma_hw2reg_dst_ptr_inc_d2_reg_t dst_ptr_inc_d2; // [140:117]
    dma_hw2reg_slot_reg_t slot; // [116:83]
    dma_hw2reg_src_data_type_reg_t src_data_type; // [82:80]
    dma_hw2reg_dst_data_type_reg_t dst_data_type; // [79:77]
    dma_hw2reg_sign_ext_reg_t sign_ext; // [76:75]
    dma_hw2reg_mode_reg_t mode; // [74:72]
    dma_hw2reg_hw_fifo_en_reg_t hw_fifo_en; // [71:70]
    dma_hw2reg_dim_config_reg_t dim_config; // [69:68]
    dma_hw2reg_dim_inv_reg_t dim_inv; // [67:66]
    dma_hw2reg_pad_top_reg_t pad_top; // [65:59]
    dma_hw2reg_pad_bottom_reg_t pad_bottom; // [58:52]
    dma_hw2reg_pad_right_reg_t pad_right; // [51:45]
    dma_hw2reg_pad_left_reg_t pad_left; // [44:38]
    dma_hw2reg_window_size_reg_t window_size; // [37:24]
    dma_hw2reg_window_count_reg_t window_count; // [23:15]
    dma_hw2reg_interrupt_en_reg_t interrupt_en; // [14:11]
    dma_hw2reg_transaction_ifr_reg_t transaction_ifr; // [10:10]
    dma_hw2reg_window_ifr_reg_t window_ifr; // [9:9]
    dma_hw2reg_slot_wait_counter_reg_t slot_wait_counter; // [8:0]
  } dma_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] DMA_SRC_PTR_OFFSET = 7'h 0;
  parameter logic [BlockAw-1:0] DMA_DST_PTR_OFFSET = 7'h 4;
  parameter logic [BlockAw-1:0] DMA_ADDR_PTR_OFFSET = 7'h 8;
  parameter logic [BlockAw-1:0] DMA_SIZE_D1_OFFSET = 7'h c;
  parameter logic [BlockAw-1:0] DMA_SIZE_D2_OFFSET = 7'h 10;
  parameter logic [BlockAw-1:0] DMA_STATUS_OFFSET = 7'h 14;
  parameter logic [BlockAw-1:0] DMA_SRC_PTR_INC_D1_OFFSET = 7'h 18;
  parameter logic [BlockAw-1:0] DMA_SRC_PTR_INC_D2_OFFSET = 7'h 1c;
  parameter logic [BlockAw-1:0] DMA_DST_PTR_INC_D1_OFFSET = 7'h 20;
  parameter logic [BlockAw-1:0] DMA_DST_PTR_INC_D2_OFFSET = 7'h 24;
  parameter logic [BlockAw-1:0] DMA_SLOT_OFFSET = 7'h 28;
  parameter logic [BlockAw-1:0] DMA_SRC_DATA_TYPE_OFFSET = 7'h 2c;
  parameter logic [BlockAw-1:0] DMA_DST_DATA_TYPE_OFFSET = 7'h 30;
  parameter logic [BlockAw-1:0] DMA_SIGN_EXT_OFFSET = 7'h 34;
  parameter logic [BlockAw-1:0] DMA_MODE_OFFSET = 7'h 38;
  parameter logic [BlockAw-1:0] DMA_HW_FIFO_EN_OFFSET = 7'h 3c;
  parameter logic [BlockAw-1:0] DMA_DIM_CONFIG_OFFSET = 7'h 40;
  parameter logic [BlockAw-1:0] DMA_DIM_INV_OFFSET = 7'h 44;
  parameter logic [BlockAw-1:0] DMA_PAD_TOP_OFFSET = 7'h 48;
  parameter logic [BlockAw-1:0] DMA_PAD_BOTTOM_OFFSET = 7'h 4c;
  parameter logic [BlockAw-1:0] DMA_PAD_RIGHT_OFFSET = 7'h 50;
  parameter logic [BlockAw-1:0] DMA_PAD_LEFT_OFFSET = 7'h 54;
  parameter logic [BlockAw-1:0] DMA_WINDOW_SIZE_OFFSET = 7'h 58;
  parameter logic [BlockAw-1:0] DMA_WINDOW_COUNT_OFFSET = 7'h 5c;
  parameter logic [BlockAw-1:0] DMA_INTERRUPT_EN_OFFSET = 7'h 60;
  parameter logic [BlockAw-1:0] DMA_TRANSACTION_IFR_OFFSET = 7'h 64;
  parameter logic [BlockAw-1:0] DMA_WINDOW_IFR_OFFSET = 7'h 68;
  parameter logic [BlockAw-1:0] DMA_HW_CONFIG_MODE_OFFSET = 7'h 6c;
  parameter logic [BlockAw-1:0] DMA_SLOT_WAIT_COUNTER_OFFSET = 7'h 70;

  // Reset values for hwext registers and their fields
  parameter logic [1:0] DMA_STATUS_RESVAL = 2'h 1;
  parameter logic [0:0] DMA_STATUS_READY_RESVAL = 1'h 1;
  parameter logic [0:0] DMA_STATUS_WINDOW_DONE_RESVAL = 1'h 0;
  parameter logic [0:0] DMA_TRANSACTION_IFR_RESVAL = 1'h 0;
  parameter logic [0:0] DMA_TRANSACTION_IFR_FLAG_RESVAL = 1'h 0;
  parameter logic [0:0] DMA_WINDOW_IFR_RESVAL = 1'h 0;
  parameter logic [0:0] DMA_WINDOW_IFR_FLAG_RESVAL = 1'h 0;

  // Register index
  typedef enum int {
    DMA_SRC_PTR,
    DMA_DST_PTR,
    DMA_ADDR_PTR,
    DMA_SIZE_D1,
    DMA_SIZE_D2,
    DMA_STATUS,
    DMA_SRC_PTR_INC_D1,
    DMA_SRC_PTR_INC_D2,
    DMA_DST_PTR_INC_D1,
    DMA_DST_PTR_INC_D2,
    DMA_SLOT,
    DMA_SRC_DATA_TYPE,
    DMA_DST_DATA_TYPE,
    DMA_SIGN_EXT,
    DMA_MODE,
    DMA_HW_FIFO_EN,
    DMA_DIM_CONFIG,
    DMA_DIM_INV,
    DMA_PAD_TOP,
    DMA_PAD_BOTTOM,
    DMA_PAD_RIGHT,
    DMA_PAD_LEFT,
    DMA_WINDOW_SIZE,
    DMA_WINDOW_COUNT,
    DMA_INTERRUPT_EN,
    DMA_TRANSACTION_IFR,
    DMA_WINDOW_IFR,
    DMA_HW_CONFIG_MODE,
    DMA_SLOT_WAIT_COUNTER
  } dma_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] DMA_PERMIT [29] = '{
    4'b 1111, // index[ 0] DMA_SRC_PTR
    4'b 1111, // index[ 1] DMA_DST_PTR
    4'b 1111, // index[ 2] DMA_ADDR_PTR
    4'b 0011, // index[ 3] DMA_SIZE_D1
    4'b 0011, // index[ 4] DMA_SIZE_D2
    4'b 0001, // index[ 5] DMA_STATUS
    4'b 0001, // index[ 6] DMA_SRC_PTR_INC_D1
    4'b 0111, // index[ 7] DMA_SRC_PTR_INC_D2
    4'b 0001, // index[ 8] DMA_DST_PTR_INC_D1
    4'b 0111, // index[ 9] DMA_DST_PTR_INC_D2
    4'b 1111, // index[10] DMA_SLOT
    4'b 0001, // index[11] DMA_SRC_DATA_TYPE
    4'b 0001, // index[12] DMA_DST_DATA_TYPE
    4'b 0001, // index[13] DMA_SIGN_EXT
    4'b 0001, // index[14] DMA_MODE
    4'b 0001, // index[15] DMA_HW_FIFO_EN
    4'b 0001, // index[16] DMA_DIM_CONFIG
    4'b 0001, // index[17] DMA_DIM_INV
    4'b 0001, // index[18] DMA_PAD_TOP
    4'b 0001, // index[19] DMA_PAD_BOTTOM
    4'b 0001, // index[20] DMA_PAD_RIGHT
    4'b 0001, // index[21] DMA_PAD_LEFT
    4'b 0011, // index[22] DMA_WINDOW_SIZE
    4'b 0001, // index[23] DMA_WINDOW_COUNT
    4'b 0001, // index[24] DMA_INTERRUPT_EN
    4'b 0001, // index[25] DMA_TRANSACTION_IFR
    4'b 0001, // index[26] DMA_WINDOW_IFR
    4'b 0001, // index[27] DMA_HW_CONFIG_MODE
    4'b 0001  // index[28] DMA_SLOT_WAIT_COUNTER
  };

endpackage

