[library.xheep_dma:ip:dma]
location = .
sync-uri = .
sync-type = local
auto-sync = true

[library.xheep_dma:tb:dma_tb]
location = .
sync-uri = .
sync-type = local
auto-sync = true

[library.pulp-platform.org::common_cells]
location = .
sync-uri = vendor
sync-type = local
auto-sync = true

[library.pulp-platform.org::register_interface]
location = ./vendor
sync-uri = vendor
sync-type = local
auto-sync = true

[library.lowrisc:prim:subreg:0]
location = ./vendor
sync-uri = vendor
sync-type = local
auto-sync = true

